implemented NullableArray{T,N}(dims...)
JuliaStats/NullableArrays.jl pull request #152
Opened 2016-10-03 03:09 UTC by gustafsson

This is needed for instance when I have a NullableArray `A` of some type and want to create another one of the same type with only nulls in it like so: `typeof(A)(size(A)...)`

2016-10-03 14:23 UTC, nalimilan commented on src/constructors.jl
> +    @compat (::Type{NullableArray{T,2}}){T,N}(x1, x2) = NullableArray(T, x1, x2)
Why define these on 0.4 but not on 0.5? Performance?

2016-10-03 14:42 UTC, davidagold commented
Is there any reason you can't use `similar`?

```julia
julia> A = collect(1:4)
4-element Array{Int64,1}:
 1
 2
 3
 4

julia> X = NullableArray(A)
4-element NullableArrays.NullableArray{Int64,1}:
 1
 2
 3
 4

julia> Y = similar(X)
4-element NullableArrays.NullableArray{Int64,1}:
 #NULL
 #NULL
 #NULL
 #NULL
```

2016-11-01 16:06 UTC, gustafsson commented on src/constructors.jl
> +    @compat (::Type{NullableArray{T,2}}){T,N}(x1, x2) = NullableArray(T, x1, x2)
On 0.5 a single function takes care of all of them.

2016-11-01 16:09 UTC, gustafsson commented
@davidagold `similar` is a good idea. I could do something like `similar(T(),3,2,1)` when I only have the type of a NullableArray but not an instance. Is it possible to do without creating an empty instance of T (perhaps it gets optimised away anyways?).

2016-11-01 16:38 UTC, gustafsson commented
I don't need this anymore.

2016-11-01 18:47 UTC, nalimilan commented
I think it would still be good to have.

2016-11-01 20:08 UTC, gustafsson commented
@nalimilan ok, I fixed the errors on v"0.4"

2016-11-02 09:57 UTC, nalimilan commented on src/constructors.jl
>  @compat (::Type{NullableArray{T}}){T}(dims::Int...) = NullableArray(T, dims)
Is this definition still useful?

2016-11-02 16:10 UTC, gustafsson commented on src/constructors.jl
>  @compat (::Type{NullableArray{T}}){T}(dims::Int...) = NullableArray(T, dims)
It's needed in order to do things like `NullableArray{Int}(3,2)`.

But a call to `NullableArray{T}(dims::Int...)` can always be replace by `NullableArray{T}((dims::Int...))` to call the other constructor with `::Dims` instead.

2016-11-02 22:08 UTC, nalimilan commented on src/constructors.jl
>  @compat (::Type{NullableArray{T}}){T}(dims::Int...) = NullableArray(T, dims)
Ah, right, I thought `N` could be inferred automatically in your new constructor, but that doesn't work for the call overloading syntax.

2016-11-02 22:09 UTC, nalimilan approved these changes

2016-11-07 22:10 UTC, nalimilan commented
@davidagold Good to merge?

2016-11-07 22:12 UTC, ararslan requested changes

2016-11-07 22:12 UTC, ararslan commented on src/constructors.jl
> +  end
Please use 4 space indents for consistency with the rest of the repo.

2016-11-08 18:35 UTC, davidagold commented
What's the failure?

2016-11-08 19:15 UTC, ararslan approved these changes

2016-11-08 19:16 UTC, ararslan commented
Changed my review since my comments were addressed, but I think the cause of the test failure should be determined before this is merged.

2016-11-08 19:35 UTC, gustafsson commented
I don't see how the error is related to this PR. v0.4 and v0.5 pass. but not nightly. does the tests currently pass on master?

2016-11-08 22:12 UTC, nalimilan commented
The error is unrelated, I'm able to reproduce it on master too. Trying to figure out what's going on...

2016-11-13 10:38 UTC, nalimilan commented
All is green now, merging.

2016-11-13 10:38 UTC, merged

2016-11-13 10:43 UTC, nalimilan commented
Damn, I screwed up and forgot to squash. Squashed and force-pushed manually.