remove @doc's and add spaces before function signatures
JuliaStats/NullableArrays.jl pull request #162
Opened 2016-10-13 21:39 UTC by RatanRSur

Shamelessly took the low hanging fruit :)

2016-10-13 22:16 UTC, ararslan commented
Thanks for the contribution!

As an aside, it's best not to use the `@` symbol at all in commit messages, since it actually ends up sending a notification to the user with that name. In this case, [this person](https://github.com/doc) has gotten or will get a notification. I think the common practice is to say `at-doc` or `doc macro`, etc. in commit messages. If you'd like, you can `git commit --amend` and then force push to your branch.

So that GitHub will auto-close the issue once this is merged: Fixes #159

2016-10-13 22:17 UTC, ararslan requested changes

2016-10-13 22:17 UTC, ararslan commented on src/broadcast.jl
> +            `broadcast!(f, B::NullableArray, As::NullableArray...; lift::Bool=false)`
When these are indented, the backticks should be removed.

2016-10-14 01:42 UTC, RatanRSur commented
Oh, cool I did not know that about @'s. Thanks!

Let me know if there are more changes.

2016-10-14 01:48 UTC, ararslan commented on src/indexing.jl
>  """ ->
The arrows at the end of the doc strings should also go; they aren't part of the new syntax.

2016-10-14 01:52 UTC, RatanRSur commented on src/indexing.jl
>  """ ->
Done, also I noticed I messed up and used 3 space indents so I fixed that as well

2016-10-14 03:02 UTC, ararslan approved these changes

2016-10-14 03:03 UTC, ararslan commented
@davidagold Is the nightly failure a known issue?

2016-10-14 08:18 UTC, nalimilan requested changes
Thanks! Looks good apart from a few details.

2016-10-14 08:18 UTC, nalimilan commented on src/broadcast.jl
>          This method implements the same behavior as that of `broadcast!` when called on
Missing line break here.

2016-10-14 08:18 UTC, nalimilan commented on src/primitives.jl
> -""" ->
This empty comment is weird, probably time to remove it.

2016-10-14 08:18 UTC, nalimilan commented on src/typedefs.jl
> +    NullableArray{T, N} is an efficient alternative to `Array{Nullable{T}, N}`.
This line isn't a signature, it's just a sentence, so keep it as it was previously.

2016-10-14 08:19 UTC, nalimilan commented
@ararslan The nightly failure is known, that's a problem with `broadcast`.

2016-10-14 18:01 UTC, ararslan commented on src/typedefs.jl
> +    NullableArray{T, N} is an efficient alternative to `Array{Nullable{T}, N}`.
Thanks for the thorough review, @nalimilan, and for catching some stuff I missed!

2016-11-17 08:56 UTC, nalimilan approved these changes

2016-11-17 12:26 UTC, nalimilan commented
Woops, completely forgot about this. It's no longer October, but let's pretend it is...

2016-11-17 12:26 UTC, merged