Ensure that `copy` also copies the `parent` field
JuliaStats/NullableArrays.jl pull request #202
Opened 2017-08-15 18:05 UTC by spurll

Closes #199

2017-08-15 18:52 UTC, spurll commented
Hm, I think that Codecov report is wrong, since I didn't touch most of those impacted files.

However, I realise that I'll need to make another commit to solve an outstanding issue related to sorting `DataTables`, so I'm going to mark this WiP.

2017-08-15 20:29 UTC, ararslan commented
> Hm, I think that Codecov report is wrong

Yeah, coverage is weird.

> However, I realise that I'll need to make another commit to solve an outstanding issue related to sorting DataTables

Is that directly related to this change?

2017-08-15 21:47 UTC, spurll commented
The problem I'm currently trying to solve is the fact that the new `NullableArray` created by `getindex` doesn't maintain the parent reference either:

```julia
julia> str = "something"
"something"

julia> arr = [WeakRefString(pointer(str, 1), 4, 1), WeakRefString(pointer(str, 5), 5, 5)]
2-element Array{WeakRefString{UInt8},1}:
 "some" 
 "thing"

julia> na = NullableArray{WeakRefString{UInt8}, 1}(arr, [false, false], Vector{UInt8}(str))
2-element NullableArrays.NullableArray{WeakRefString{UInt8},1}:
 "some" 
 "thing"

julia> na.parent
9-element Array{UInt8,1}:
 0x73
 0x6f
 0x6d
 0x65
 0x74
 0x68
 0x69
 0x6e
 0x67

julia> na[:].parent
0-element Array{UInt8,1}
```

It's certainly related, though maybe it warrants a separate PR.

2017-08-16 17:18 UTC, spurll commented
This should now be good to go. Though it's possible that the change I made to `similar` will be contentious, it is necessary to maintain the parent reference without massive changes to the codebase.

2017-08-22 17:31 UTC, nalimilan approved these changes
Thanks, this makes sense, though that `parent` field is really an ugly hack... I'd like a check by @quinnj, who introduced this feature.

2017-08-22 17:33 UTC, nalimilan requested changes
Woops, I had missed some details.

2017-08-22 17:33 UTC, nalimilan commented on test/indexing.jl
> +    @test isequal(x[1:2].parent, x.parent)
Use `===` Same below..

2017-08-22 18:13 UTC, spurll commented on test/indexing.jl
> +    @test isequal(x[1:2].parent, x.parent)
Thanks. I've made that change, and the corresponding change to test/primitives.jl as well.

2017-08-22 19:09 UTC, quinnj approved these changes
This looks fine. I have new code in WeakRefStrings that introduces a WeakRefStringArray so that we don't need this kind of `parent` field anymore. I'm going to try and do new releases for all of DataStreams this week that uses it.

2017-08-22 22:04 UTC, merged